# Generated by Django 3.0.2 on 2020-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiries',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('Pending', 'Pending')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
